const PortfolioActionTypes = {
    SET_CURRENT_PORTFOLIO: 'SET_CURRENT_PORTFOLIO',
    SET_CURRENT_PORTFOLIO_SLIDE : 'SET_CURRENT_PORTFOLIO_SLIDE',
    SET_PORTFOLIO_LIST: 'SET_PORTFOLIO_LIST',

};

export default PortfolioActionTypes;